chore: add deprecations for PerformTouchAction and PerformMultiAction…
appium/appium-dotnet-driver pull request #553
Opened 2022-11-09 21:25 UTC by Dor-bl

## Change list

Missed this one while pushing https://github.com/appium/appium-dotnet-driver/pull/548

## Types of changes

What types of changes are you proposing/introducing to .NET client?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] New feature (non-breaking change which adds value to the project)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Documentation
- [ ] Have you proposed a file change/ PR with appium to update documentation? 
#### This can be done by navigating to the documentation section on http://appium.io selecting the appropriate command/endpoint and clicking the 'Edit this doc' link to update the C# example

## Integration tests
- [ ] Have you provided integration tests to pass against the beta version of appium? (for Bugfix or New feature)

## Details

Please provide more details about changes if it is necessary. If there are new features you can provide code samples which show the way they
work and possible use cases. Also you can create [gists](https://gist.github.com) with pasted C# code samples or put them here using markdown. 
About markdown please read [Mastering markdown](https://guides.github.com/features/mastering-markdown/) and [Writing on GitHub](https://help.github.com/categories/writing-on-github/)

2022-11-09 22:34 UTC, KazuCocoa approved these changes

2022-11-10 22:36 UTC, akinsolb commented
I'm not sure what's going on with my previous PR comments but these methods need the [Obsolete] attribute in order to see it in usage & build time

2022-11-11 05:42 UTC, Dor-bl commented
What PR comments? The last PR was approved w/o any comments.

2022-11-11 12:03 UTC, akinsolb requested changes

2022-11-11 12:11 UTC, Dor-bl commented on src/Appium.Net/Appium/AppiumDriver.cs
> +        // TODO: Remove this region once we deprecate the touch actions
You can't really add obsolete attribute to regions AFAIK,but I'll add it to the methods that I've missed.

2022-11-11 13:53 UTC, akinsolb approved these changes

2022-11-11 15:32 UTC, merged